# Generated by Django 4.2.2 on 2023-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_recurring_bill_repeatevery_recurringbill_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bill',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='recurring_bill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
