# Generated by Django 4.2.2 on 2023-09-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_recurring_bill_bill_no_recurring_bill_billno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_terms',
        ),
    ]
