# Generated by Django 4.2.2 on 2023-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
