# Generated by Django 4.2.2 on 2023-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_recurring_bill_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringbill_item',
            old_name='amount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='recurringbill_item',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='recurringbill_item',
            old_name='rate',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='recurringbill_item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recurringbill_item',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recurringbill_item',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
