# Generated by Django 4.2.2 on 2023-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_amount_recurringbill_item_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='adjustment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
