# Generated by Django 4.2.2 on 2023-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_recurring_bill_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='paid_amount',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
    ]
