# Generated by Django 4.2.2 on 2023-09-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_recurring_bill_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
