# Generated by Django 4.2.2 on 2023-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_recurring_bill_cgst_alter_recurring_bill_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
