# Generated by Django 4.2.2 on 2023-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_recurring_bill_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='adjustment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
